default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: d0ub!E2Three20!8postgresql
  timeout: 5000

development:
  <<: *default
  database: hello_rails_development
  adapter: postgresql
  encoding: unicode
  username: postgres

test:
  <<: *default
  database: hello_rails_development
  adapter: postgresql
  encoding: unicode
  username: postgres

production:
  <<: *default
  database: hello_rails_production
